config/routes.rb
Rails.application.routes.draw do
  resources :reservas
  resources :carros
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'importacao/new' => 'importacao#new'
  post 'importacao/create' => 'importacao#create'

  root 'carros#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carro.rb
class Carro < ApplicationRecord
	validates :marca, presence: true
    validates :modelo, presence: true, :uniqueness => true
end

app/models/reserva.rb
class Reserva < ApplicationRecord
	belongs_to :carro, class_name: "Carro"
	validates :responsavel, presence: true
    validates :carro_id, presence: true, :uniqueness => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: [:show, :edit, :update, :destroy, :importar]
  before_action :authenticate_user!

  # GET /carros
  # GET /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1
  # GET /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros
  # POST /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to @carro, notice: 'Carro was successfully created.' }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1
  # PATCH/PUT /carros/1.json
  def update
    respond_to do |format|
      if (!carro_params[:disponivel].present?)
        carro_params[:disponivel] = false
      end

      if @carro.update(carro_params)
        format.html { redirect_to @carro, notice: 'Carro was successfully updated.' }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1
  # DELETE /carros/1.json
  def destroy
    @carro.destroy
    respond_to do |format|
      format.html { redirect_to carros_url, notice: 'Carro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carro_params
      params.fetch(:carro, {}).permit(:marca,:disponivel, :modelo)
    end
end

app/controllers/importacao_controller.rb
require 'csv'

class ImportacaoController < ApplicationController
	def new
		
	end

	def create
		uploaded_io = params[:arquivo]
		caminho = Rails.root.join('public', 'uploads', uploaded_io.original_filename)

		if File.exist?(caminho)
			FileUtils.rm_rf Dir.glob("#{Rails.root}/public/uploads/*")
		end

		File.open(caminho, 'wb') do |file|
		  file.write(uploaded_io.read)
		end

		CSV.foreach(caminho, col_sep: ';').with_index do |linha, indice|
			unless (indice == 0)
       			Carro.create!(marca: linha[0], modelo: linha[1], disponivel: true)
     		end
		end

		respond_to do |format|
            format.html { redirect_to carros_url, notice: 'Importação Realizada com Sucesso!' }
        end
	end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @carros = Carro.where(:disponivel => true)
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
    @carros = Carro.where(:disponivel => true)
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)
    @carros = Carro.where(:disponivel => true)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    @carros = Carro.where(:disponivel => true)

    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.fetch(:reserva, {}).permit(:responsavel,:carro_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/helpers/importacao_helper.rb
module ImportacaoHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/carros/_form.html.erb
<%= form_with(model: carro, local: true) do |form| %>
  <% if carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
      <% carro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

  <%= form.label :marca %>
  <%= form.text_field :marca %>

  <%= form.label :modelo %>
  <%= form.text_field :modelo %>

  <%= form.label :disponivel %>
  <%= form.select :disponivel, [['Não', false], ['Sim', true]] %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carros/edit.html.erb
<h1>Edição Dados - Carros</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

app/views/carros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carros</h1>

<% if user_signed_in? %>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% end %>
&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to "Importar Carros(.csv)", importacao_new_path %>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Disponivel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carros.each do |carro| %>
      <tr>
        <td><%= carro.id %></td>
        <td><%= carro.marca %></td>
        <td><%= carro.modelo %></td>
        <td><%= carro.disponivel ? 'Sim' : 'Não' %></td>
        <td><%= link_to 'Exibir', carro %></td>
        <td><%= link_to 'Editar', edit_carro_path(carro) %></td>
        <td><%= link_to 'Excluir', carro, method: :delete, data: { confirm: 'Deseja realmente Excluir o Registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Novo', new_carro_path %>

app/views/carros/new.html.erb
<h1>New Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Back', carros_path %>

app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Dados - Carro</h1>

<p>
    <strong>Marca</strong>
    <%= @carro.marca %>
</p>

<p>
    <strong>Modelo</strong>
    <%= @carro.modelo %>
</p>

<p>
    <strong>Disponível</strong>
    <%= @carro.disponivel ? 'Sim' : 'Não' %>
</p>

<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>

app/views/importacao/new.html.erb
<h1>Importação de Carros</h1>
<%= form_tag("/importacao/create", method: "post", multipart: true) do %>
  <input type="file" name="arquivo">
	<button type="submit">Importar</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Provarails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/reservas/_form.html.erb
<%= form_with(model: reserva, local: true) do |form| %>
  <% if reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
      <% reserva.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :responsavel %>
  <%= form.text_field :responsavel %>

  <%= form.label :carro_id %>
  <%= form.select :carro_id, @carros.collect { |carro| [carro.marca + " - " + carro.modelo, carro.id] }%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<h1>Editing Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table>
  <thead>
    <th>#</th>
    <th>Responsável Reserva</th>
    <th>Marca</th>
    <th>Modelo</th>
    <th>Data Reserva</th>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.id %></td>
         <td><%= reserva.responsavel %></td>
        <td><%= reserva.carro.marca %></td>
        <td><%= reserva.carro.modelo %></td>
        <td><%= reserva.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= link_to 'Exibir', reserva %></td>
        <td><%= link_to 'Editar', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Excluir', reserva, method: :delete, data: { confirm: 'Excluir Reserva?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Reserva', new_reserva_path %>

app/views/reservas/new.html.erb
<h1>New Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Back', reservas_path %>

app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Dados - Reserva</h1>
<p>
    <strong>#</strong>
    <%= @reserva.id %>
</p>
<p>
    <strong>Responsável</strong>
    <%= @reserva.responsavel %>
</p>

<p>
    <strong>Marca</strong>
    <%= @reserva.carro.marca %>
</p>

<p>
    <strong>Modelo</strong>
   <%= @reserva.carro.modelo %>
</p>


<p>
    <strong>Data da Reserva</strong>
    <%= @reserva.created_at.strftime("%d/%m/%Y") %>
</p>



<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>